name: codeReview

on:
  pull_request:
    branches:
      - main

jobs:
  ESLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
      - name: install
        run: yarn install
      - name: ESLint
        run: yarn fix:eslint
  Prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
      - name: install
        run: yarn install
      - name: Prettier
        run: yarn fix:prettier
  UnitTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
      - name: install
        run: yarn install
      - name: test
        run: yarn test